name: phylostability
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - iqtree
  - biopython
  - ete3
  - seaborn
  - matplotlib
  - python
  - epa-ng
  - scikit-learn
  - optuna
  - pypythia=1.1.4
  - pandas
